# Generated by Django 4.0.3 on 2022-06-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Info')),
                ('photo', models.ImageField(blank=True, upload_to='photos/&Y/%m/&d/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Food menu ',
                'verbose_name_plural': 'Foods menu',
            },
        ),
    ]
